modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="anomaly_foundation_mod"
version="1.0.0"
displayName="Anomaly Foundation Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="user, MCreator"

[[dependencies.anomaly_foundation_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




